name: AWS ECR With Appleboy Plugin
on: [push]

env:
  AWS_REGION : ap-northeast-1

jobs:

  build:
    name: upload image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: upload image to ECR
      uses: appleboy/docker-ecr-action@v0.0.2
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        registry: ${{ secrets.REGISTRY }}
        repo: ${{ secrets.TEST_REPO }}
        region: ap-northeast-1
        auto_tag: true
