name: AWS ECR With ECR Plugin
on: [push]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION : ap-northeast-1

jobs:

  build:
    name: upload image
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '^1'
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build binary
        run : |
          make build_linux_amd64
          make build_linux_arm64

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.API_REPO }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --build-arg TARGETOS=linux --build-arg TARGETARCH=amd64 -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest
