name: Upload Docker Image
on: [push]

permissions:
  id-token: write
  contents: read

jobs:

  build:
    name: upload image
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '^1'
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build binary
        run : |
          make build_linux_amd64
          make build_linux_arm64
